{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Setup"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Turn on autoreload. All modules will be reloaded before excecuting each cell. Even objects that already exist will receive the new method defintions."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Import stuff."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import logging\n",
    "import sys\n",
    "import os\n",
    "import atexit\n",
    "\n",
    "sys.path.insert(0, os.path.join(os.getcwd(), \"..\"))\n",
    "from cirrus import automate, GridSearch, LogisticRegression, graph"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Configure logging so that debug-level log messages are printed."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "log = logging.getLogger(\"cirrus\")\n",
    "log.setLevel(logging.DEBUG)\n",
    "log.addHandler(logging.StreamHandler(sys.stdout))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Done on release"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Create the server image (and an instance for that purpose)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "instance_for_server_image = automate.Instance(\n",
    "    \"cirrus_instance_for_server_image\",\n",
    "    ami_id=\"ami-04403d81a81d1a5da\",\n",
    "    disk_size=32,\n",
    "    typ=\"m5.2xlarge\",\n",
    "    username=\"ec2-user\"\n",
    ")\n",
    "instance_for_server_image.start()\n",
    "automate.make_server_image(\n",
    "    \"cirrus_server_image\",\n",
    "    \"s3://cirrus-public/from_shared_vm/executables\",\n",
    "    instance_for_server_image\n",
    ")\n",
    "instance_for_server_image.cleanup()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Make the lambda package."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "make_lambda_package: Initializing ZIP file.\n",
      "make_lambda_package: Writing handler.\n",
      "make_lambda_package: Initializing S3.\n",
      "make_lambda_package: Downloading executable.\n",
      "make_lambda_package: Writing executable.\n",
      "make_lambda_package: Uploading package.\n",
      "make_lambda_package: Waiting for changes to take effect.\n",
      "make_lambda_package: Done.\n"
     ]
    }
   ],
   "source": [
    "automate.make_lambda_package(\n",
    "    \"s3://cirrus-public-us-west-2/1/lambda-package\",\n",
    "    \"s3://cirrus-public/from_shared_vm/executables\"\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Done by user"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Make the lambda."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "automate.make_lambda(\"cirrus_worker\", \"s3://cirrus-public-us-west-2/1/lambda-package\", 100)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Make the instance for the parameter servers."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "__init__: Initializing EC2.\n",
      "__init__: Resolving AMI name to AMI ID.\n",
      "__init__: Done.\n",
      "start: Calling _make_instance_profile.\n",
      "_make_instance_profile: Initializing IAM.\n",
      "_make_instance_profile: Creating role.\n",
      "_make_instance_profile: Attaching policy to role.\n",
      "_make_instance_profile: Creating instance profile.\n",
      "_make_instance_profile: Adding role to instance profile.\n",
      "_make_instance_profile: Waiting for changes to take effect.\n",
      "_make_instance_profile: Done.\n",
      "start: Calling _make_key_pair.\n",
      "_make_key_pair: Creating new key pair.\n",
      "_make_key_pair: Saving private key.\n",
      "_make_key_pair: Fetching key metadata.\n",
      "_make_key_pair: Done.\n",
      "start: Calling _make_security_group.\n",
      "_make_security_group: Creating new security group.\n",
      "_make_security_group: Configuring security group.\n",
      "_make_security_group: Done.\n",
      "start: Calling _start_and_wait.\n",
      "_start_and_wait: Starting a new instance.\n",
      "_start_and_wait: Waiting for instance to enter running state.\n",
      "_start_and_wait: Fetching instance metadata.\n",
      "_start_and_wait: Done.\n",
      "start: Done.\n"
     ]
    }
   ],
   "source": [
    "instance_for_ps = automate.Instance(\n",
    "    \"cirrus_instance_for_ps\",\n",
    "    ami_name=\"cirrus_server_image\",\n",
    "    disk_size=32,\n",
    "    typ=\"m5.2xlarge\",\n",
    "    username=\"ec2-user\"\n",
    ")\n",
    "instance_for_ps.start()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Define the logistic regression configuration."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "basic_params = {\n",
    "    'n_workers': 16,\n",
    "    'n_ps': 1,\n",
    "    'lambda_size': 128,\n",
    "    'dataset': \"criteo-kaggle-19b\",\n",
    "    'learning_rate': 0.001,\n",
    "    'epsilon': 0.0001,\n",
    "    'progress_callback': None,\n",
    "    'timeout': 60,\n",
    "    'opt_method': 'adagrad',\n",
    "    'minibatch_size': 200,\n",
    "    'model_bits': 19,\n",
    "    'train_set': (0,6),\n",
    "    'test_set': (7,8)\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Start a grid search."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "start: Uploading configuration.\n",
      "start: Starting parameter server.\n",
      "start: Retreiving parameter server PID.\n",
      "start: Starting error task.\n",
      "start: Retreiving error task PID.\n",
      "launch_worker: Launching Task 0.\n",
      "launch_worker: Launching Task 10000.\n",
      "launch_worker: Launching Task 20000.\n",
      "launch_worker: Launching Task 30000.\n",
      "launch_worker: Launching Task 40000.\n",
      "launch_worker: Launching Task 60000.\n",
      "launch_worker: Launching Task 50000.\n",
      "launch_worker: Launching Task 70000.\n",
      "launch_worker: Launching Task 80000.\n",
      "launch_worker: Launching Task 90000.\n",
      "launch_worker: Launching Task 100000.\n",
      "launch_worker: Launching Task 110000.\n",
      "launch_worker: Launching Task 120000.\n",
      "launch_worker: Launching Task 130000.\n",
      "launch_worker: Launching Task 140000.\n",
      "start: Uploading configuration.\n",
      "ClientManager: Initializing Lambda client.\n",
      "launch_worker: Launching Task 150000.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "ClientManager: Initializing Lambda client.\n",
      "start: Starting parameter server.\n",
      "ClientManager: Initializing Lambda client.\n",
      "start: Retreiving parameter server PID.\n",
      "start: Starting error task.\n",
      "start: Retreiving error task PID.\n",
      "launch_worker: Task 0 completed with status code 200.\n",
      "launch_worker: Task 110000 completed with status code 200.\n",
      "Sleeping for 119.281968117\n",
      "launch_worker: Task 50000 completed with status code 200.\n",
      "Sleeping for 119.285647154\n",
      "launch_worker: Task 10000 completed with status code 200.\n",
      "Sleeping for 119.281280994\n",
      "Sleeping for 119.277247906\n",
      "launch_worker: Task 100000 completed with status code 200.\n",
      "Sleeping for 119.277849913\n",
      "launch_worker: Task 150000 completed with status code 200.\n",
      "Sleeping for 119.27472496\n",
      "launch_worker: Task 90000 completed with status code 200.\n",
      "Sleeping for 119.269008875\n",
      "launch_worker: Task 20000 completed with status code 200.\n",
      "launch_worker: Task 30000 completed with status code 200.\n",
      "Sleeping for 119.248283863\n",
      "Sleeping for 119.247393131\n",
      "launch_worker: Task 40000 completed with status code 200.\n",
      "Sleeping for 119.243149996\n",
      "launch_worker: Task 70000 completed with status code 200.\n",
      "Sleeping for 119.235031128\n",
      "launch_worker: Task 140000 completed with status code 200.\n",
      "Sleeping for 119.231602907\n",
      "launch_worker: Task 130000 completed with status code 200.\n",
      "Sleeping for 119.20559597\n",
      "launch_worker: Task 120000 completed with status code 200.\n",
      "Sleeping for 119.160636902\n",
      "launch_worker: Task 80000 completed with status code 200.\n",
      "Sleeping for 117.934774876\n",
      "launch_worker: Task 60000 completed with status code 200.\n",
      "Sleeping for 115.94943881\n",
      "launch_worker: Launching Task 10000000.\n",
      "launch_worker: Launching Task 10010000.\n",
      "launch_worker: Launching Task 10020000.\n",
      "launch_worker: Launching Task 10030000.\n",
      "launch_worker: Launching Task 10040000.\n",
      "launch_worker: Launching Task 10050000.\n",
      "launch_worker: Launching Task 10060000.\n",
      "launch_worker: Launching Task 10070000.\n",
      "launch_worker: Launching Task 10080000.\n",
      "launch_worker: Launching Task 10090000.\n",
      "launch_worker: Launching Task 10100000.\n",
      "launch_worker: Launching Task 10110000.\n",
      "launch_worker: Launching Task 10120000.\n",
      "launch_worker: Launching Task 10130000.\n",
      "launch_worker: Launching Task 10140000.\n",
      "launch_worker: Launching Task 10150000.\n",
      "start: Uploading configuration.\n",
      "start: Starting parameter server.\n",
      "start: Retreiving parameter server PID.\n",
      "start: Starting error task.\n",
      "start: Retreiving error task PID.\n",
      "launch_worker: Task 10040000 completed with status code 200.\n",
      "Sleeping for 119.839267969\n",
      "launch_worker: Task 10000000 completed with status code 200.\n",
      "launch_worker: Task 10050000 completed with status code 200.\n",
      "Sleeping for 119.8276999\n",
      "Sleeping for 119.834614038\n",
      "launch_worker: Task 10030000 completed with status code 200.\n",
      "launch_worker: Task 10010000 completed with status code 200.\n",
      "Sleeping for 119.820152998\n",
      "launch_worker: Task 10080000 completed with status code 200.\n",
      "Sleeping for 119.816025019\n",
      "launch_worker: Task 10020000 completed with status code 200.\n",
      "Sleeping for 119.82434392\n",
      "launch_worker: Task 10070000 completed with status code 200.\n",
      "Sleeping for 119.812067986\n",
      "launch_worker: Task 10060000 completed with status code 200.\n",
      "Sleeping for 119.818118095\n",
      "launch_worker: Task 10100000 completed with status code 200.\n",
      "Sleeping for 119.815295935\n",
      "launch_worker: Task 10090000 completed with status code 200.\n",
      "Sleeping for 119.818435907\n",
      "Sleeping for 119.816242933\n",
      "launch_worker: Task 10110000 completed with status code 200.\n",
      "launch_worker: Task 10130000 completed with status code 200.\n",
      "Sleeping for 119.808783054\n",
      "Sleeping for 119.807902098\n",
      "launch_worker: Task 10150000 completed with status code 200.\n",
      "launch_worker: Task 10120000 completed with status code 200.\n",
      "Sleeping for 119.799394846\n",
      "Sleeping for 119.796631813\n",
      "launch_worker: Task 10140000 completed with status code 200.\n",
      "Sleeping for 119.793143988\n",
      "launch_worker: Launching Task 20000000.\n",
      "launch_worker: Launching Task 20010000.\n",
      "launch_worker: Launching Task 20020000.\n",
      "launch_worker: Launching Task 20030000.\n",
      "launch_worker: Launching Task 20040000.\n",
      "launch_worker: Launching Task 20050000.\n",
      "launch_worker: Launching Task 20060000.\n",
      "launch_worker: Launching Task 20070000.\n",
      "launch_worker: Launching Task 20080000.\n",
      "launch_worker: Launching Task 20090000.\n",
      "launch_worker: Launching Task 20100000.\n",
      "launch_worker: Launching Task 20110000.\n",
      "launch_worker: Launching Task 20120000.\n",
      "launch_worker: Launching Task 20130000.\n",
      "launch_worker: Launching Task 20140000.\n",
      "launch_worker: Launching Task 20150000.\n",
      "start: Uploading configuration.\n",
      "start: Starting parameter server.\n",
      "start: Retreiving parameter server PID.\n",
      "start: Starting error task.\n",
      "start: Retreiving error task PID.\n",
      "launch_worker: Task 20010000 completed with status code 200.\n",
      "Sleeping for 119.852194071\n",
      "launch_worker: Task 20020000 completed with status code 200.\n",
      "launch_worker: Task 20030000 completed with status code 200.\n",
      "Sleeping for 119.841732979\n",
      "launch_worker: Task 20000000 completed with status code 200.\n",
      "Sleeping for 119.839926004\n",
      "launch_worker: Task 20040000 completed with status code 200.\n",
      "Sleeping for 119.835303068\n",
      "Sleeping for 119.84009099\n",
      "launch_worker: Task 20070000 completed with status code 200.\n",
      "launch_worker: Task 20060000 completed with status code 200.\n",
      "Sleeping for 119.836355925\n",
      "launch_worker: Task 20050000 completed with status code 200.\n",
      "Sleeping for 119.833612919\n",
      "Sleeping for 119.831537962\n",
      "launch_worker: Task 20090000 completed with status code 200.\n",
      "Sleeping for 119.832325935\n",
      "launch_worker: Task 20080000 completed with status code 200.\n",
      "Sleeping for 119.825242996\n",
      "launch_worker: Task 20100000 completed with status code 200.\n",
      "Sleeping for 119.826334953\n",
      "launch_worker: Task 20140000 completed with status code 200.\n",
      "Sleeping for 119.821264982\n",
      "launch_worker: Task 20120000 completed with status code 200.\n",
      "Sleeping for 119.815134048\n",
      "launch_worker: Task 20110000 completed with status code 200.\n",
      "launch_worker: Task 20150000 completed with status code 200.\n",
      "Sleeping for 119.806676149\n",
      "launch_worker: Task 20130000 completed with status code 200.\n",
      "Sleeping for 119.808182001\n",
      "Sleeping for 119.805654049\n",
      "launch_worker: Launching Task 30000000.\n",
      "launch_worker: Launching Task 30010000.\n",
      "launch_worker: Launching Task 30020000.\n",
      "launch_worker: Launching Task 30030000.\n",
      "launch_worker: Launching Task 30040000.\n",
      "launch_worker: Launching Task 30050000.\n",
      "launch_worker: Launching Task 30060000.\n",
      "launch_worker: Launching Task 30070000.\n",
      "launch_worker: Launching Task 30080000.\n",
      "launch_worker: Launching Task 30090000.\n",
      "launch_worker: Launching Task 30100000.\n",
      "launch_worker: Launching Task 30110000.\n",
      "launch_worker: Launching Task 30120000.\n",
      "launch_worker: Launching Task 30130000.\n",
      "launch_worker: Launching Task 30140000.\n",
      "launch_worker: Launching Task 30150000.\n",
      "run_command: Calling _connect_ssh.\n",
      "_connect_ssh: Configuring.\n",
      "_connect_ssh: Making connection attempt #1 out of 10.\n",
      "launch_worker: Task 30020000 completed with status code 200.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sleeping for 119.801254988launch_worker: Task 30040000 completed with status code 200.\n",
      "\n",
      "launch_worker: Task 30000000 completed with status code 200.\n",
      "Sleeping for 119.805773973\n",
      "launch_worker: Task 30010000 completed with status code 200.\n",
      "Sleeping for 119.794450998\n",
      "launch_worker: Task 30050000 completed with status code 200.\n",
      "Sleeping for 119.793909073\n",
      "launch_worker: Task 30030000 completed with status code 200.\n",
      "Sleeping for 119.800063133\n",
      "Sleeping for 119.7954638\n",
      "launch_worker: Task 30080000 completed with status code 200.\n",
      "Sleeping for 119.79794693\n",
      "launch_worker: Task 30060000 completed with status code 200.\n",
      "Sleeping for 119.791181087launch_worker: Task 30140000 completed with status code 200.\n",
      "\n",
      "launch_worker: Task 30120000 completed with status code 200.\n",
      "Sleeping for 119.788357973\n",
      "launch_worker: Task 30130000 completed with status code 200.\n",
      "Sleeping for 119.781265974\n",
      "launch_worker: Task 30100000 completed with status code 200.\n",
      "Sleeping for 119.778739929\n",
      "launch_worker: Task 30150000 completed with status code 200.\n",
      "Sleeping for 119.775296211\n",
      "launch_worker: Task 30110000 completed with status code 200.\n",
      "Sleeping for 119.775577068\n",
      "launch_worker: Task 30090000 completed with status code 200.\n",
      "Sleeping for 119.771320105\n",
      "launch_worker: Task 30070000 completed with status code 200.\n",
      "Sleeping for 119.768913984\n",
      "Sleeping for 119.763950109\n",
      "run_command: Running `echo 'load_input_path: /mnt/efs/criteo_kaggle/train.csv \n",
      "load_input_type: csv\n",
      "dataset_format: binary\n",
      "num_classes: 2 \n",
      "num_features: 13 \n",
      "limit_cols: 14 \n",
      "normalize: 0 \n",
      "limit_samples: 10000 \n",
      "s3_size: 50000 \n",
      "use_bias: 1 \n",
      "model_type: LogisticRegression \n",
      "minibatch_size: 200 \n",
      "learning_rate: 0.001000 \n",
      "epsilon: 0.000100 \n",
      "model_bits: 19 \n",
      "s3_bucket: criteo-kaggle-19b \n",
      "use_grad_threshold: 0 \n",
      "grad_threshold: 0.001000 \n",
      "train_set: 0-6 \n",
      "test_set: 7-8' > config_1337.txt\n",
      "nohup ./parameter_server --config config_1337.txt --nworkers 32 --rank 1 --ps_port 1337 &> ps_out_1337 &\n",
      "echo $! > ps_1337.pid\n",
      "nohup ./parameter_server --config config_1337.txt --nworkers 32 --rank 2 --ps_ip 172.31.19.70 --ps_port 1337 &> error_out_1337 &\n",
      "echo $! > error_1337.pid\n",
      "echo 'load_input_path: /mnt/efs/criteo_kaggle/train.csv \n",
      "load_input_type: csv\n",
      "dataset_format: binary\n",
      "num_classes: 2 \n",
      "num_features: 13 \n",
      "limit_cols: 14 \n",
      "normalize: 0 \n",
      "limit_samples: 10000 \n",
      "s3_size: 50000 \n",
      "use_bias: 1 \n",
      "model_type: LogisticRegression \n",
      "minibatch_size: 200 \n",
      "learning_rate: 0.010000 \n",
      "epsilon: 0.000100 \n",
      "model_bits: 19 \n",
      "s3_bucket: criteo-kaggle-19b \n",
      "use_grad_threshold: 0 \n",
      "grad_threshold: 0.001000 \n",
      "train_set: 0-6 \n",
      "test_set: 7-8' > config_1339.txt\n",
      "nohup ./parameter_server --config config_1339.txt --nworkers 32 --rank 1 --ps_port 1339 &> ps_out_1339 &\n",
      "echo $! > ps_1339.pid\n",
      "nohup ./parameter_server --config config_1339.txt --nworkers 32 --rank 2 --ps_ip 172.31.19.70 --ps_port 1339 &> error_out_1339 &\n",
      "echo $! > error_1339.pid\n",
      "echo 'load_input_path: /mnt/efs/criteo_kaggle/train.csv \n",
      "load_input_type: csv\n",
      "dataset_format: binary\n",
      "num_classes: 2 \n",
      "num_features: 13 \n",
      "limit_cols: 14 \n",
      "normalize: 0 \n",
      "limit_samples: 10000 \n",
      "s3_size: 50000 \n",
      "use_bias: 1 \n",
      "model_type: LogisticRegression \n",
      "minibatch_size: 200 \n",
      "learning_rate: 0.100000 \n",
      "epsilon: 0.000100 \n",
      "model_bits: 19 \n",
      "s3_bucket: criteo-kaggle-19b \n",
      "use_grad_threshold: 0 \n",
      "grad_threshold: 0.001000 \n",
      "train_set: 0-6 \n",
      "test_set: 7-8' > config_1341.txt\n",
      "nohup ./parameter_server --config config_1341.txt --nworkers 32 --rank 1 --ps_port 1341 &> ps_out_1341 &\n",
      "echo $! > ps_1341.pid\n",
      "nohup ./parameter_server --config config_1341.txt --nworkers 32 --rank 2 --ps_ip 172.31.19.70 --ps_port 1341 &> error_out_1341 &\n",
      "echo $! > error_1341.pid\n",
      "echo 'load_input_path: /mnt/efs/criteo_kaggle/train.csv \n",
      "load_input_type: csv\n",
      "dataset_format: binary\n",
      "num_classes: 2 \n",
      "num_features: 13 \n",
      "limit_cols: 14 \n",
      "normalize: 0 \n",
      "limit_samples: 10000 \n",
      "s3_size: 50000 \n",
      "use_bias: 1 \n",
      "model_type: LogisticRegression \n",
      "minibatch_size: 200 \n",
      "learning_rate: 1.000000 \n",
      "epsilon: 0.000100 \n",
      "model_bits: 19 \n",
      "s3_bucket: criteo-kaggle-19b \n",
      "use_grad_threshold: 0 \n",
      "grad_threshold: 0.001000 \n",
      "train_set: 0-6 \n",
      "test_set: 7-8' > config_1343.txt\n",
      "nohup ./parameter_server --config config_1343.txt --nworkers 32 --rank 1 --ps_port 1343 &> ps_out_1343 &\n",
      "echo $! > ps_1343.pid\n",
      "nohup ./parameter_server --config config_1343.txt --nworkers 32 --rank 2 --ps_ip 172.31.19.70 --ps_port 1343 &> error_out_1343 &\n",
      "echo $! > error_1343.pid`.\n",
      "run_command: Waiting for completion.\n",
      "run_command: Exit code was 0.\n",
      "run_command: Fetching stdout and stderr.\n",
      "run_command: stdout had length 0.\n",
      "run_command: stderr had length 0.\n",
      "run_command: Done.\n"
     ]
    }
   ],
   "source": [
    "os.system(\"aws logs delete-log-group --log-group-name /aws/lambda/cirrus_worker\")\n",
    "gs = GridSearch(\n",
    "    task=LogisticRegression,\n",
    "    param_base=basic_params,\n",
    "    hyper_vars=[\"learning_rate\"],\n",
    "    hyper_params=[[0.001, 0.01, 0.1, 1]],\n",
    "    instances=[instance_for_ps]\n",
    ")\n",
    "gs.set_threads(1)\n",
    "gs.run(UI=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "View the progress of the experiment."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "graph.display_dash()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Utilities"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Write the SSH key for the instance to a file."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open(\"key.pem\", \"w+\") as f:\n",
    "    f.write(instance_for_ps.private_key())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "View the instance's public IP address."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "instance_for_ps.public_ip()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "View the output of the parameter server of the first experiment."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "gs.cirrus_objs[0].ps.error_output()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "gs.cirrus_objs[0].ps.ps_output()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "concurrency_limit: Querying the Lambda's concurrency limit.\n",
      "run_command: Running `kill -9 $(cat error_1337.pid)`.\n",
      "run_command: Waiting for completion.\n",
      "run_command: Exit code was 0.\n",
      "run_command: Fetching stdout and stderr.\n",
      "run_command: stdout had length 0.\n",
      "run_command: stderr had length 0.\n",
      "run_command: Done.\n",
      "run_command: Running `kill -9 $(cat ps_1337.pid)`.\n",
      "run_command: Waiting for completion.\n",
      "run_command: Exit code was 0.\n",
      "run_command: Fetching stdout and stderr.\n",
      "run_command: stdout had length 0.\n",
      "run_command: stderr had length 0.\n",
      "run_command: Done.\n",
      "run_command: Running `kill -9 $(cat error_1339.pid)`.\n",
      "run_command: Waiting for completion.\n",
      "run_command: Exit code was 0.\n",
      "run_command: Fetching stdout and stderr.\n",
      "run_command: stdout had length 0.\n",
      "run_command: stderr had length 0.\n",
      "run_command: Done.\n",
      "run_command: Running `kill -9 $(cat ps_1339.pid)`.\n",
      "run_command: Waiting for completion.\n",
      "run_command: Exit code was 0.\n",
      "run_command: Fetching stdout and stderr.\n",
      "run_command: stdout had length 0.\n",
      "run_command: stderr had length 0.\n",
      "run_command: Done.\n",
      "run_command: Running `kill -9 $(cat error_1341.pid)`.\n",
      "run_command: Waiting for completion.\n",
      "run_command: Exit code was 0.\n",
      "run_command: Fetching stdout and stderr.\n",
      "run_command: stdout had length 0.\n",
      "run_command: stderr had length 0.\n",
      "run_command: Done.\n",
      "run_command: Running `kill -9 $(cat ps_1341.pid)`.\n",
      "run_command: Waiting for completion.\n",
      "run_command: Exit code was 0.\n",
      "run_command: Fetching stdout and stderr.\n",
      "run_command: stdout had length 0.\n",
      "run_command: stderr had length 0.\n",
      "run_command: Done.\n",
      "run_command: Running `kill -9 $(cat error_1343.pid)`.\n",
      "run_command: Waiting for completion.\n",
      "run_command: Exit code was 0.\n",
      "run_command: Fetching stdout and stderr.\n",
      "run_command: stdout had length 0.\n",
      "run_command: stderr had length 0.\n",
      "run_command: Done.\n",
      "run_command: Running `kill -9 $(cat ps_1343.pid)`.\n",
      "run_command: Waiting for completion.\n",
      "run_command: Exit code was 1.\n",
      "run_command: Fetching stdout and stderr.\n",
      "run_command: stdout had length 0.\n",
      "run_command: stderr had length 46.\n",
      "run_command: Done.\n",
      "launch_worker: Launching Task 1.\n",
      "launch_worker: Launching Task 40001.\n",
      "launch_worker: Launching Task 50001.\n",
      "launch_worker: Launching Task 60001.\n",
      "launch_worker: Launching Task 20001.\n",
      "launch_worker: Launching Task 70001.\n",
      "launch_worker: Launching Task 30001.\n",
      "launch_worker: Launching Task 90001.\n",
      "launch_worker: Launching Task 110001.\n",
      "launch_worker: Launching Task 100001.\n",
      "launch_worker: Launching Task 10001.\n",
      "launch_worker: Launching Task 120001.\n",
      "launch_worker: Launching Task 130001.\n",
      "launch_worker: Launching Task 80001.\n",
      "launch_worker: Launching Task 140001.\n",
      "launch_worker: Launching Task 150001.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Worker 0:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 13:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 5:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 4:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 6:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 2:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 9:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 7:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 11:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 12:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 10:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 8:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 15:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 14:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "launch_worker: Launching Task 10000001.\n",
      "launch_worker: Launching Task 10010001.\n",
      "launch_worker: Launching Task 10020001.\n",
      "launch_worker: Launching Task 10030001.\n",
      "launch_worker: Launching Task 10040001.\n",
      "launch_worker: Launching Task 10050001.\n",
      "launch_worker: Launching Task 10060001.\n",
      "launch_worker: Launching Task 10080001.\n",
      "launch_worker: Launching Task 10070001.\n",
      "launch_worker: Launching Task 10140001.\n",
      "launch_worker: Launching Task 10150001.\n",
      "launch_worker: Launching Task 10120001.\n",
      "launch_worker: Launching Task 10130001.\n",
      "launch_worker: Launching Task 10110001.\n",
      "launch_worker: Launching Task 10100001.\n",
      "launch_worker: Launching Task 10090001.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Worker 1000:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1001:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1002:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1004:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1003:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1005:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1008:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1006:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1007:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1014:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1015:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1012:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1013:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1011:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1010:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 1009:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "launch_worker: Launching Task 20010001.\n",
      "launch_worker: Launching Task 20000001.\n",
      "launch_worker: Launching Task 20030001.\n",
      "launch_worker: Launching Task 20020001.\n",
      "launch_worker: Launching Task 20040001.\n",
      "launch_worker: Launching Task 20050001.\n",
      "launch_worker: Launching Task 20070001.\n",
      "launch_worker: Launching Task 20080001.\n",
      "launch_worker: Launching Task 20060001.\n",
      "launch_worker: Launching Task 20110001.\n",
      "launch_worker: Launching Task 20120001.\n",
      "launch_worker: Launching Task 20100001.\n",
      "launch_worker: Launching Task 20090001.\n",
      "launch_worker: Launching Task 20130001.\n",
      "launch_worker: Launching Task 20150001.\n",
      "launch_worker: Launching Task 20140001.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Worker 2001:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 2003:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "Exception in thread Worker 2000:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "\n",
      "Exception in thread Worker 2002:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 2004:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 2007:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "Exception in thread Worker 2005:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "Exception in thread Worker 2008:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "\n",
      "\n",
      "Exception in thread Worker 2006:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 2011:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 2012:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 2010:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 2009:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 2013:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 2015:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 2014:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "launch_worker: Launching Task 30000001.\n",
      "launch_worker: Launching Task 30010001.\n",
      "launch_worker: Launching Task 30020001.\n",
      "launch_worker: Launching Task 30030001.\n",
      "launch_worker: Launching Task 30040001.\n",
      "launch_worker: Launching Task 30050001.\n",
      "launch_worker: Launching Task 30070001.\n",
      "launch_worker: Launching Task 30080001.\n",
      "launch_worker: Launching Task 30110001.\n",
      "launch_worker: Launching Task 30090001.\n",
      "launch_worker: Launching Task 30100001.\n",
      "launch_worker: Launching Task 30060001.\n",
      "launch_worker: Launching Task 30120001.\n",
      "launch_worker: Launching Task 30130001.\n",
      "launch_worker: Launching Task 30140001.\n",
      "launch_worker: Launching Task 30150001.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Worker 3000:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3002:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3001:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3003:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3004:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3007:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3005:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3008:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3011:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "Exception in thread Worker 3009:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "\n",
      "Exception in thread Worker 3010:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3006:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3013:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3015:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3014:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n",
      "Exception in thread Worker 3012:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 801, in __bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py\", line 754, in run\n",
      "    self.__target(*self.__args, **self.__kwargs)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1087, in maintain_one\n",
      "    launch_worker(lambda_name, task_id, config, n, ps)\n",
      "  File \"/Users/shea/Google Drive/-/Work/Cirrus/Repositories/Fixes/python/frontend/cirrus/examples/../cirrus/automate.py\", line 1036, in launch_worker\n",
      "    Payload=json.dumps(payload)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 320, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/usr/local/lib/python2.7/site-packages/botocore/client.py\", line 623, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-west-2:142598916558:function:cirrus_worker\n",
      "\n"
     ]
    }
   ],
   "source": [
    "gs.kill_all()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Create a new SSH connection to the instance. Useful when the connection times out while you're aware from the computer."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "instance_for_ps._connect_ssh()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Do cleanup. Normally this is called on exit, but Jupyter does not reliably allow this to complete."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "cleanup: Closing SSH client.\n",
      "cleanup: Terminating instance.\n",
      "cleanup: Waiting for instance to terminate.\n"
     ]
    }
   ],
   "source": [
    "atexit._run_exitfuncs()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
